linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49 CPPSTD=98
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49 CPPSTD=11
    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=conanio/gcc49 CPPSTD=14
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5 CPPSTD=98
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5 CPPSTD=11
    - <<: *linux
      env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5 CPPSTD=14
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CPPSTD=98
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CPPSTD=11
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CPPSTD=14
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CPPSTD=17
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CPPSTD=98
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CPPSTD=11
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CPPSTD=14
    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CPPSTD=17
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CPPSTD=98
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CPPSTD=11
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CPPSTD=14
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CPPSTD=17
    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CPPSTD=20
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CPPSTD=98
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CPPSTD=11
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CPPSTD=14
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CPPSTD=17
    - <<: *linux
      env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CPPSTD=20
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39 CPPSTD=98
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39 CPPSTD=11
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39 CPPSTD=14
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40 CPPSTD=98
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40 CPPSTD=11
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40 CPPSTD=14
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50 CPPSTD=98
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50 CPPSTD=11
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50 CPPSTD=14
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50 CPPSTD=17
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60 CPPSTD=98
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60 CPPSTD=11
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60 CPPSTD=14
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60 CPPSTD=17
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60 CPPSTD=20
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 CPPSTD=98
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 CPPSTD=11
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 CPPSTD=14
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 CPPSTD=17
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7 CPPSTD=20
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CPPSTD=98
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CPPSTD=11
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CPPSTD=14
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CPPSTD=17
    - <<: *linux
      env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8 CPPSTD=20
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CPPSTD=98
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CPPSTD=11
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CPPSTD=14
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CPPSTD=17
    - <<: *osx
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1 CPPSTD=20
    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CPPSTD=98
    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CPPSTD=11
    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CPPSTD=14
    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CPPSTD=17
    - <<: *osx
      osx_image: xcode9.4
      env: CONAN_APPLE_CLANG_VERSIONS=9.1 CPPSTD=20
    - <<: *osx
      osx_image: xcode10.2
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CPPSTD=98
    - <<: *osx
      osx_image: xcode10.2
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CPPSTD=11
    - <<: *osx
      osx_image: xcode10.2
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CPPSTD=14
    - <<: *osx
      osx_image: xcode10.2
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CPPSTD=17
    - <<: *osx
      osx_image: xcode10.2
      env: CONAN_APPLE_CLANG_VERSIONS=10.0 CPPSTD=20

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
